### ISSUE TITLE
How do I install it in my Nexus3?

### ISSUE THREAD

**Issue by gigioSouza** [sonatype/nexus-blobstore-s3#45]
I'm using nexus as a docker image: `sonatype/nexus3:3.8.0`

I've already created a volume to the `/opt/sonatype/nexus/deploy` to a directory with the `nexus-blobstore-s3.jar` and the `aws-sdk.jar`, but I have no idea how I get into the Nexu Repository Console (as I read about it, the karaf console) to run the `bundle:start nexus-blobstore-s3` and `bundle:start aws-sdk`

My Nexus already recognize the blobstore and de aws-sdk as a bundle, but I need to start it.

![captura de tela 2018-03-12 as 12 34 49](https://user-images.githubusercontent.com/4052932/37297057-7dde75c8-25fb-11e8-823c-e727696ee0a1.png)
![captura de tela 2018-03-12 as 12 34 58](https://user-images.githubusercontent.com/4052932/37297058-7dfbec7a-25fb-11e8-8160-fd134fcad048.png)

---

My docker-compose.yml:
```
version: '3'
services:
  nexus:
    container_name: 'nexus'
    image: sonatype/nexus3:3.8.0
    ports:
      - 8081:8081
    volumes:
      - './nexus-data:/nexus-data'
      - './nexus-deploy:/opt/sonatype/nexus/deploy'
```

My `nexus-deploy`:
```
aws-java-sdk-1.11.292.jar
nexus-blobstore-s3-1.2.1-SNAPSHOT.jar
```

I already tried to follow this doc https://help.sonatype.com/display/NXRM3/Installing+Bundles
Adding `nexus-blobstore-s3` to the `nexus.properties` like:
```
nexus.features=nexus-blobstore-s3
```

But when I restart my container I got this logs:
```
...
2018-03-12 17:12:57,109+0000 INFO  [FelixStartLevel] *SYSTEM org.sonatype.nexus.bootstrap.ConfigurationBuilder -   nexus-features='nexus-blobstore-s3'
...
2018-03-12 17:13:18,592+0000 WARN  [jetty-main-1] *SYSTEM org.sonatype.nexus.extender.NexusContextListener - Missing: nexus-blobstore-s3
...
```

And it generates problemas with the `org.sonatype.nexus.extender.NexusLifecycleManager`.
